// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var Backbone, EvLayer, MapView;
    Backbone = require('backbone');
    EvLayer = require('Models/EvLayer');
    MapView = Backbone.View.extend({
      el: "div#map",
      initialize: function() {
        this.mapProvider = this.options.mapProvider;
        this.initialCenter = this.options.initialCenter || {
          lat: 39.937,
          lon: -105.0691
        };
        return this.render();
      },
      setInitialView: function() {
        return this.mapProvider.setView({
          lat: this.initialCenter.lat,
          lon: this.initialCenter.lon,
          zoomLevel: 13
        });
      },
      render: function() {
        this.mapProvider.createMap(this.el.id);
        this.mapProvider.addLayer(EvLayer);
        return this.setInitialView();
      }
    });
    return MapView;
  });

}).call(this);
