// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var $, App, AppRouter, Backbone, router;
    $ = require('jquery');
    Backbone = require('backbone');
    router = require('router');
    AppRouter = router.AppRouter;
    return App = {
      start: function() {
        new AppRouter();
        return Backbone.history.start({
          pushState: true
        });
      }
    };
  });

}).call(this);
